FedoraQt/MediaWriter

build/build.sh
build/mediawriter-configure
build/org.fedoraproject.MediaWriter.json

for MediaWriter. To make my life easier, I decided to
just use the kde runtime, which has all the qt5 bits
in it.
Sadly, the build currently fails, with an error that
I can't make sense of. Maybe you can give it a quick look ?
To try this out, just
cd build
./build.sh org.fedoraproject.MediaWriter.json

Here is some initial work towards flatpak packaging

---

helper/linux/writejob.h
helper/mac/writejob.cpp
helper/mac/writejob.h
helper/win/writejob.cpp
helper/win/writejob.h

* Remove from linux helper since it's not used anymore since 397c29857c4a2d7cb3699319b0c8b871b9ffc582.
* Remove from windows helper since it's not used anymore since 92032e6fdb8165733998d5a106f0987a65e8e370.
* Remove from mac helper since it was never used.

Remove unused variable dd

---

app/linuxdrivemanager.cpp

Set status before detaching `m_image` as intended by 4b001dddc17d47d892393f6d46286e746aeed6e7.
Fix crash by not trying to call an object pointer on null.
Probably the commit message is bad. I'm open to suggestions.

Correct statement order

---

helper/linux/writejob.cpp
helper/linux/writejob.h

Fix memory leak in WriteJob::writeCompressed of the linux helper.
~~Use C++14 for the linux helper so that `std::make_unique` can be used.~~
So this is an interesting case to review in my humbly opinion. As you can see I used the STL and it wasn't used in this project before. So I hope that there is stuff to talk about.

Improve memory management of page-aligned buffer

---

dist/win/mediawriter.nsi

This is a bunch of fixes for when the app is installed in Windows using the NSIS script.
This commit has 3 minor changes:
1. Changes the app name from `"${PUBLISHER} - ${APP_NAME} - ${DESCRIPTION}"` to just `"${APP_NAME}"`
(Now it's corrected to `Fedora Media Writer` instead of `Fedora Project - Fedora Media Writer - Tool to write Fedora images to flash drives`).
2. Icon has been fixed - a silly "typo" crept in pointing to a non-existent file
(Icon filename is corrected to `~\mediawriter.ico` instead of `~\logo.ico`.
3. Removed quotes from the help strings URIs.
**Pending task**: Investigation pending on why `${VERSIONMAJOR}` and other version numbers along with `${INSTALLSIZE}` aren't being populated during build-time. One cue would be the `build.sh` which is responsible for inflating …

Fixed Windows Uninstaller information

---

app/linuxdrivemanager.cpp
app/macdrivemanager.cpp
app/windrivemanager.cpp

Moved calls to progress bar setTo and setValue from DriveManager::write()  to DriveManager::onReadyRead().
Takes care of the case where delayedWrite() calls write() too early before file size is known causing the "to" value to be 0 and progress bar value to be invalid for the whole writing process.

fix progress bar not showing when delayed writing

---

dist/linux/mediawriter.appdata.xml
dist/linux/mediawriter.appdata.xml.in

fixes:
```
$ flatpak run org.freedesktop.appstream-glib validate mediawriter.appdata.xml
mediawriter.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• tag-missing           : <release> required
```

appdata.xml: add content_rating & releases

---

src/app/data/org.fedoraproject.MediaWriter.desktop
src/app/data/org.fedoraproject.MediaWriter.desktop.in

This makes FMW easier to find using the words 'fmw,usb,iso,bootable'
Closes: #291

Add keywords to .desktop

---

src/app/CMakeLists.txt
src/app/main.cpp
src/app/portalfiledialog.cpp
src/app/portalfiledialog.h
src/app/qml/DelegateImage.qml
src/app/qml/main.qml

There is a bug in QML file dialog [1] causing file dialog freeze in some cases. This should workaround this issue.
Fixes: https://github.com/FedoraQt/MediaWriter/issues/277 and https://github.com/FedoraQt/MediaWriter/issues/339
RH Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1977472
[1] - https://bugreports.qt.io/browse/QTBUG-59184

Use portal file dialog when possible to avoid native dialog issues

---

src/app/qml/ImageList.qml

Adds ability to select MediaWriter's version number via the mouse so it
may be copied.

Make version number selectable

---

src/app/releasemanager.cpp

Use Intel/AMD 64bit and Intel/AMD 32bit names for architectures

---

src/app/releasemanager.cpp

With the new UI it doesn't have to be at the third position to potentially replace other variant.

Add custom image variant to the end of the list

---

src/helper/win/restorejob.cpp

This will hopefully fix https://github.com/FedoraQt/MediaWriter/issues/464.

Windows: format to exFAT instead of FAT32

---

src/app/utilities.h

With the F38 release, getfedora.org is going to be replaced with fedoraproject.org.
The new URL for releases.json will be https://fedoraproject.org/releases.json

Update URL for releases.json

---

src/app/macdrivearbiter.mm

Mac Drive Manager only recognized USB connections, this also checks if the drive is an SD connection.
Notice "Connection: USB"
Notice "Connection: Secure Digital" (which stands for SD, not sure why Apple chose to go with this)
With this Apple's builtin SD card reader works,
Note this doesn't affect USB SD Card Readers, because those were always under Connection USB (Same SD card):
And for completeness sake, here's the side by side before and after the commit.
Pretty simple but important change.

Recognize Internal SD Card Reader on MacOS

---

src/helper/linux/restorejob.cpp

The newly created partition cannot start on offset 0, previously UDisks was able to compensate for this, but there is a bug in the latest UDisks/libblockdev and this no longer works. But in general offset 0 for a new partition doesn't make sense. We can also use 0 for size to let UDisks calculate the maximal size instead of passing the underlying device size.
Fixes: #644
----
Note that we still plan to fix the UDisks/libblockdev bug, but I think it makes sense to change the values for offset and size here to make the code more future proof -- the 0 offset would never work, so you'd see the udisks warning anyway and having us calculate the max size could avoid some rounding/alignment issues in the future.

Fix restore on Linux with latest UDisks/libblockdev

---

.github/workflows/pr-check.yml
.github/workflows/release.yml

Current universal build doesn't work. I added another job to build a separate macOS arm64 version. Having them separated also reduces the size of the application.
Closes #380

Add macOS arm64 build

---

src/app/data/assets/metadata.json
src/app/qml/VersionPage.qml
src/app/releasemanager.cpp

Changed the text descriptions for the new Atomic Desktop branding.
See: https://fedoramagazine.org/introducing-fedora-atomic-desktops/
Closes: #684

Updating emerging editions to Atomic Desktop

---

src/app/CMakeLists.txt
src/helper/win/CMakeLists.txt

By specifying the UAC level in the manifest, the program will trigger a UAC prompt upon launch. Thus the helper will launch with administrator privileges:
We initially added the UAC level to the helper, however the way how `helper.exe` is launched does not allow the UAC prompt to pop up[^1]. Using alternative APIs can resolve this, but it would require a rewrite to apply the workaround, namely `QProcess::startDetached()`, which launches a new process that can not be managed by `QProcess`.
[^1]: https://learn.microsoft.com/en-us/windows/win32/dxtecharts/user-account-control-for-game-developers?redirectedfrom=MSDN#uac-implications-with-createprocess

chore: specify UAC level to `requireAdministrator` in the manifest for Windows

---

po/build-translations.sh

This pull request contains two scripting errors in `po/build-translations` that should hopefully make the (currently manual) Qt translation generation procedures simpler:
- Output `*.qm` and `*.qrc` directly to `/src/translations`.
- Automatically convert `pt-BR`, `zh-CN`, and `zh-TW` language tags to `pt_BR`, `zh_CN`, and `zh_TW`.

Fixes for po/build-translations.sh

---

src/app/qml/DownloadPage.qml

The original code incorrectly (and unnecessarily?) calculates the width of the string before the displayed unit, causing the size number and unit to overlap.
Dropping this line fixes this issue.

fix(qml/DownloadPage): fix download remaining size display

---

README.md

Removing `adwaita-qt` as one of the requirements for Linux, per [discussion here](https://github.com/FedoraQt/MediaWriter/issues/706#event-12347448404).

Update README.md, removing `adwaita-qt` as requirement

---

src/app/qml.qrc
src/app/qml/DeviceWarningDialog.qml
src/app/qml/DrivePage.qml
src/app/qml/main.qml

It can happen that the user connects a drive by mistake or forgets to disconnect it, and it's unfortunate if the drive is accidentally erased. In this case, display a warning dialogue that the user is using a drive larger than 32GB.
Fixes #742

Show a warning dialog in case we are going to erase drive > 32GB

---

.github/workflows/clang-format-check.yml
src/app/CMakeLists.txt
src/app/main.cpp
src/app/utilities.h
src/app/windrivemanager.cpp
src/app/windrivemanager.h
src/helper/win/CMakeLists.txt
src/helper/win/main.cpp
src/helper/win/restorejob.cpp
src/helper/win/restorejob.h
src/helper/win/writejob.cpp
src/helper/win/writejob.h
src/lib/CMakeLists.txt
src/lib/libwindisk/CMakeLists.txt
src/lib/libwindisk/windisk.cpp
src/lib/libwindisk/windisk.h

This is a complete rewrite of the Windows support. It introduces a new library 'libwindisk' that combines use of WMI and WinAPI to manipulate with devices. We use Windows Storage Management for getting information about devices and some actions, especially since pure WinAPI does not seem to have support for things like formatting or partition removal. This library is used in both the app and the helper process used for writing and formatting. We now also don't rely on diskpart since it didn't work properly in some cases.
Fixes #626 | Fixes #575 | Fixes #574 |Fixes #555 | Fixes #96

Windows: complete rewrite of drive restoration and image writing

---

src/app/qml/Page.qml

Wrap the heading in case of a longer text and elide it to the right side in case the number of lines exceeds two lines (won't probably happen).

Fix overfloating heading for longer texts

---

src/app/main.cpp

Using QLocale::system() gives the correct locale, but uiLanguages() can give us language we don't want to. Instead just construct a new QLocale with the language reported as primary by QLocale::system().
Fixes #271

Fix language detection

---

src/helper/linux/CMakeLists.txt
src/helper/linux/job.cpp
src/helper/linux/job.h
src/helper/linux/restorejob.cpp
src/helper/linux/restorejob.h
src/helper/linux/writejob.cpp

Similar to Windows, overwrite the beginning of the drive and the end of the drive with zeroes before creating a new partition table. This is to make sure there are no partition table residues after a Fedora image was written onto the drive.
Resolves #575

Linux: overwrite start and end of the drive with zeroes when restoring

---

src/app/drivemanager.cpp

1PB = 1000TB
It seems like a small mistake. I wanna fix it although this unit is rarely used now.

fix units typo issue

---

src/app/releasemanager.cpp

Some URLs, like oci images or qemu images are not used by FMW so we can filter these out. Also don't replace '_' in release name with a space as it breaks kde_mobile spin and design_suite lab images.

Fix listing of additional spin/labs images and filter out unused urls

---

dist/win/mediawriter.nsi
dist/win/mediawriter_native.nsi

Quoting NSIS's [Reference/$PROGRAMFILES](https://nsis.sourceforge.io/Reference/$PROGRAMFILES) doc:
> The program files directory (usually `C:\Program Files` but detected at runtime). On Windows x64, `$PROGRAMFILES` and `$PROGRAMFILES32` point to `C:\Program Files (x86)` while `$PROGRAMFILES64` points to `C:\Program Files`. Use `$PROGRAMFILES64` when installing x64 applications.
Fixes #791

Install Fedora Media Writer to 'C:\Program Files' on Windows x64

---

src/app/main.cpp

QGuiApplication::SetDesktopFileName() expects the name to be without the ".desktop" suffix

Properly set desktop file name

---

src/app/releasemanager.cpp

This warning message is useless, instead put it into a debug.

Do not warn about unsupported architectures
