FedoraQt/MediaWriter

- app/components/RestoreDialog.qml
Anders Jonsson pointed this out while reviewing my Swedish translation.
> Fix a trivial misspelling.

- dist/win/build.sh
Make sure that `mingw32-qt5-qmake` is installed since it's being used and it can't be assumed that it is installed already.
> Make sure that mingw qmake is installed before use

- PRIVACY.md
https://github.com/MartinBriza/MediaWriter/issues/137
> fix grammar in PRIVACY.md

- dist/win/build.sh
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
> Windows build fixes: Abort on error and wine.i686

- dist/mac/build.sh
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>
> Add instructions for Mac notarization

- app/app.pro
- app/macdrivemanager.cpp
- dist/mac/build.sh
- helper/mac/writejob.cpp
- helper/mac/writejob.h
This makes it work on Mac OSX Catalina
Initial code made by @MartinBriza
Closes https://github.com/FedoraQt/MediaWriter/issues/217
> Use authopen binary to get read/write access to USB disks

- dist/win/build.sh
Signed-off-by: Tomas Hrcka <thrcka@redhat.com>
> Use both license files in win build script

- dist/win/build.sh
- dist/win/mediawriter.nsi
- dist/win/mediawriter_native.nsi
Signed-off-by: Tomas Hrcka <thrcka@redhat.com>
> Use different time-stamping server

- README.md
Thanks in advance for reviewing.
> Switch to Weblate translations

- .github/workflows/ccpp.yml
> Publish testing flatpaks to GitHub release page

- src/app/main.cpp
- src/app/qml/DrivePage.qml
Fixed of enabling nextButton while comming back from DrivePage and enabling MessageHandler
> Fixed enabling buttons

- src/app/qml/DownloadPage.qml
- src/app/qml/RestorePage.qml
- src/app/qml/main.qml
Text changed to "back" and prevButton renamed to backButton
> Updated prevButton

- .github/workflows/ccpp.yml
> Produce both Flatpak and Windows development builds at the same time

- src/app/qml/AboutDialog.qml
- src/app/qml/CancelDialog.qml
- src/app/qml/DownloadPage.qml
- src/app/qml/DrivePage.qml
- src/app/qml/main.qml
Fixes #420 
Fixes #421 
Fixes #423
> Updated layout of dialogs and updated labels

- src/app/qml/AboutDialog.qml
- src/app/qml/main.qml
> Updated labels

- src/app/data/assets/metadata.json
> Add Fedora Jam support

- dist/flatpak/org.fedoraproject.MediaWriter.json
- src/app/qml/DrivePage.qml
- src/app/qml/Units.qml
- src/app/releasemanager.cpp
> Fix notifications in Flatpak and do not pick pre-release versions as default

- src/app/qml/AboutDialog.qml
- src/app/qml/CancelDialog.qml
- src/app/qml/main.qml
Fixes #466
Fixes #467
Fixes #468
Fixes #465
> Don't use fixed size of dialogs and main window

- src/app/linuxdrivemanager.cpp
- src/app/macdrivemanager.cpp
- src/app/windrivemanager.cpp
> Make sure to terminate helper with the main application

- src/app/qml/main.qml
> Fixed disappering restore option

- src/app/qml/CancelDialog.qml
> Fixed unclear description in cancelDialog

- src/app/qml/CancelDialog.qml
- src/app/qml/main.qml
> Make sure to show/hide option to restore device as expected

- src/app/qml/DownloadPage.qml
Fixes #513
@yarons does this make sense?
> Use better texts in window title

- src/app/qml/CancelDialog.qml
- src/app/qml/DownloadPage.qml
- src/app/qml/DrivePage.qml
- src/app/qml/main.qml
Also improve and simplify window title messages and messages in general on the download page.
Fixes #533
> Allow to download image without an USB drive plugged in

- src/app/qml/DownloadPage.qml
- src/app/qml/main.qml
Also simplify conditions checking available USB drives.
> Simplify Next/Previous button handling

- .github/workflows/ccpp.yml
- src/app/windrivemanager.cpp
- src/app/windrivemanager.h
> Check mountable USB drive on Windows in order to allow to restore it

- dist/win/build.sh
Add `libpcre2-8.0.dll` and bump `libicu` version. Also add some additional mingw packages that need to be installed.
> Update Windows script for Fedora 38

- .github/workflows/ccpp.yml
- dist/flatpak/org.fedoraproject.MediaWriter.json
> Update Flatpak to 6.5

- src/app/data/assets/metadata.json
- src/app/data/assets/releases.json
- src/app/qml/VersionPage.qml
- src/app/releasemanager.cpp
- src/app/releasemanager.h
Also fix wrong index mapping for each Fedora variant in case any of these variants don't have a downloadable ISO yet.
> Add Fedora Sericea and Fedora Onyx 

- src/app/drivemanager.cpp
- src/app/drivemanager.h
- src/app/linuxdrivemanager.cpp
> Linux: do not re-create drives on PropertiesChanged signal from Udisks2

- src/app/main.cpp
Also cleanup some unused stuff while at it.
Fixes #705
> Do not override GDK backend

- src/app/data/org.fedoraproject.MediaWriter.appdata.xml.in
https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Releases.html#tag-release-url
> Add changelog to AppStream metadata

- src/app/data/assets/metadata.json
- src/app/releasemanager.cpp
> Add Fedora KDE Mobile spin to the list

- .github/workflows/release.yml
> Fix automatic publication on WinGet

- src/app/qml/Heading.qml
- src/app/qml/MainPage.qml
- src/app/qml/Page.qml
- src/app/qml/RestorePage.qml
> QML rewrite followup: Fixes UI of some pages where content didn't fit

- src/app/qml/DeviceWarningDialog.qml
- src/app/qml/DrivePage.qml
Make the dialog to appear all the time and not only for drives bigger than 32GB.
> Show the warning dialog with erase confirmation everytime

- src/lib/libwindisk/windisk.cpp
> Windows: make USB hard drives visible

- src/lib/libwindisk/windisk.cpp
> Call CoInitializeEx() to initialize the COM library

- src/helper/win/writejob.cpp
Correctly handle offset calculation.
Fixes #793
> Fix writing of large sized ISO images

- src/app/qml/RestorePage.qml
> Unwrap line to fix translation in UI

- src/app/data/assets/metadata.json
- src/app/data/assets/releases.json
> Move KDE to official editions

- src/app/data/assets/metadata.json
- src/app/data/assets/releases.json
> Add COSMIC spin

- dist/win/mediawriter.nsi
- dist/win/mediawriter_native.nsi
@grulja 
Improve NSI installer script
- Set product version (now is 0.5.2.5)
- Set file version (now is empty)
- Set copyright message (missing year)
- Set file description (add "installer")
- Set product version on top left of caption
- Many other improvements
> Improve NSI installer script

- dist/win/mediawriter.nsi
- dist/win/mediawriter_native.nsi
@grulja 
Please merge. Thanks.
> Improve Windows installer script
